config = {}
config.wifi = {}
config.wifi.eventmon = false
config.wifi.station_cfg = {}
config.wifi.station_cfg.ssid="ssid"
config.wifi.station_cfg.pwd="password"
config.wifi.station_cfg.save=true
config.readsensor = {}
config.readsensor.topic = "sensors"
config.readsensor.measurement = "environ"
config.readsensor.location = "PSB-2fl"
config.readsensor.hostname = wifi.sta.gethostname()
config.mqtt = {}
config.mqtt.server = "172.20.10.10"
config.mqtt.port = "1883"
